logpath="log/"
[watchdog]
	step=1000 		#цикл watchdog
[setBrams]
	dbpath="db/"
	step=1
[hardware]
	step=100		#цикл опроса датчиков миллисекунд
	connect="192.168.115.159"
	sport=5000
	count=3
	longkk=3		#Длительность кругом красный
	pinos=1			#Номер входа ОС
	pinyb=2			#Номер входа ЖМ
[netware]
	port=8000       ## порт откуда ждем настройки
[rtc]
